spring:
  datasource:
    url: jdbc:sqlserver://sqlserver:1433;databaseName=football;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Perusalen123$
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  sql:
    init:
      mode: always
server:
  port: 8080
